# Dimensionality reduction on IRIS data set

In [1]:
from sklearn import datasets
X, y = datasets.load_iris(return_X_y=True)

In [2]:
from sklearn.decomposition import PCA
import numpy as np 

# Voglio mantenere il 95% della varianza totale
pca = PCA(n_components=0.95)
X_pca = pca.fit_transform(X)

pca.n_components_, pca.components_, pca.explained_variance_

(2,
 array([[ 0.36138659, -0.08452251,  0.85667061,  0.3582892 ],
        [ 0.65658877,  0.73016143, -0.17337266, -0.07548102]]),
 array([4.22824171, 0.24267075]))

In [3]:
from sklearn.model_selection import cross_val_score
from sklearn import svm 

score = cross_val_score(svm.SVC(kernel='linear', C=1), X=X, y=y, cv=3)
score

array([1.  , 1.  , 0.98])

In [4]:
score_pca = cross_val_score(svm.SVC(kernel='linear', C=1), X = X_pca, y=y, cv=3)
score_pca

array([0.98, 0.96, 0.96])

In [5]:
score.mean(), score_pca.mean()

(0.9933333333333333, 0.9666666666666667)